### ISSUE TITLE
master branch regression: tools don't print a short summary when executed without options

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-tools#1099]
On tpm2-tools 3.X executing the tools without any options prints a short summary to help users:

```
$ tpm2_create
Usage: tpm2_create [<options>]
Where <options> are:
    [ -H | --parent=<value>] [ -P | --pwdp=<value>] [ -K | --pwdk=<value>] [ -g | --halg=<value>]
    [ -G | --kalg=<value>] [ -A | --object-attributes=<value>] [ -I | --in-file=<value>] [ -L | --policy-file=<value>]
    [ -u | --pubfile=<value>] [ -r | --privfile=<value>] [ -c | --context-parent=<value>] [ -S | --input-session-handle=<value>]
```

But on the master branch, this feature doesn't work anymore:

```
$ tpm2_create
ERROR: Must specify parent object via -C
ERROR: Unable to run tpm2_create
```

**Comment by joshuagl** [comment]
There was an intentional behaviour change in [12bfda8](https://github.com/tpm2-software/tpm2-tools/commit/12bfda8) with the (relevant part of the) commit message:

> Drop the help flag. Either we show help based on -h|--help option or if a tool fails along the way in option handling.

Yet the tool here fails with an error and doesn't show the help message, therefore this does appear to be a bug.

@williamcroberts can you help us understand why the behaviour was changed and we chose to no longer show the help when a tool is run without options? It's fairly common behaviour, though not universal.

**Comment by williamcroberts** [comment]
Some tools execute without options, and adding that flag just kind of complicates things on when we should print versus when we shouldn't. Rather, just print on -h or on error early enough in the execution process. If the tool fails because, for instance, the keyahndle is not loaded, the tpm error is displayed, but theirs no need to dump the options out.

**Comment by williamcroberts** [comment]
Currently it skips on run, because dumping help in some cases won't help the user. It's really, if we're still verifying options in the "onrun" portion.

So we could modify the return values for tpm2_onrun, so -1 show help, 0 success, 1 fail.

This way tools like tpm2_create, and others can say, show short-help please.

Or we could keep this behavior and say "see help" maybe a LOG_HELP() message?

**Comment by joshuagl** [comment]
That's an elegant solution with a minimal impact on code complexity and readability -- I like it.
I have the beginnings of a patch to make that change, will likely get a PR out tomorrow.
