### ISSUE TITLE
tpm2_clearlock - bad option name on -L and rename

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1147]
The hierarchy for clearcontrol command can be either LOCKOUT or PLATFORM, but the parameter for a password is done via:
```
        { "auth-lockout",   required_argument, NULL, 'L' },
```

This should probably be -P

**Comment by williamcroberts** [comment]
The tool should also be called tpm2_clearcontrol, not clearlock.

**Comment by williamcroberts** [comment]
This -L can also be changed in tpm2_clear

**Comment by idesai** [comment]
> The tool should also be called tpm2_clearcontrol, not clearlock.

The tool is purported to block those with knowledge owner hierarchy authorization from using it to clear the TPM. 

I agree clearlock does not convey that in anyway, rather sounds like it would clear a lockout :)

On a real TPM the owner hierarchy losing it's ability to clear the tpm is a big deal especially since the only way to resolve the situation is to get access to the platform hierarchy which is potentially more difficult on a real platform unless platform firmware has provisions for it.

I feel very tempted to break this tool into two explicit operations:
1. tpm2_disable_clear : this can take owner auth and platform auth
2. tpm2_enable_clear : this can only take platform auth

**Comment by idesai** [comment]
@williamcroberts any thoughts on this ?

**Comment by williamcroberts** [comment]
> > The tool should also be called tpm2_clearcontrol, not clearlock.
> 
> The tool is purported to block those with knowledge owner hierarchy authorization from using it to clear the TPM.
> 
> I agree clearlock does not convey that in anyway, rather sounds like it would clear a lockout :)
> 
> On a real TPM the owner hierarchy losing it's ability to clear the tpm is a big deal especially since the only way to resolve the situation is to get access to the platform hierarchy which is potentially more difficult on a real platform unless platform firmware has provisions for it.
> 
> I feel very tempted to break this tool into two explicit operations:
> 
> 1. tpm2_disable_clear : this can take owner auth and platform auth
> 2. tpm2_enable_clear : this can only take platform auth

No we want the tool name to be close to the TPM command so people can go from spec knowledge to tools easily. The command is clearcontrol, thus tpm2_clearcontrol.

And then make the option names reasonable. We should be specifying hierarchy as a option input:
--hierarchy=<o|l> with it defaulting to platform or lockout (whichever is reasonable) and convert the command line option via a call to `tpm2_hierarchy_from_optarg()` and then a required *argument* of 0|1|set|clear

So using the tool would look like:
```sh
tpm2_clearcontrol --hierarchy=lockout -p foobar set
tpm2_clearcontrol --hierarchy=lockout -p foobar clear
```

**Comment by idesai** [comment]
@williamcroberts sounds good. I was thinking to default it to platform hierarchy. The reasoning being if someone simply runs this tool inadvertently without any parameters, it would at least prevent from this command taking effect on a real TPM wherein the platform hierarchy auth is not readily available.
Event if using lockout authorization default or not, should we caution the user before proceeding or simply execute?
