### ISSUE TITLE
test_tpm2_quote.sh result is fail

### ISSUE THREAD

**Issue by miraelim** [tpm2-software/tpm2-tools#1259]
I got an error when I did test_tpm2_quote.sh
when I simply did tpm2_quote -k 0x81010004 -G sha1 -l 16,17,18 -m message.txt -s sign.txt, it did not return any thing.
but, when I see echo $?, it printed 1 ( it means fail) and the sign.txt and message.txt did not created.
how do i solve it?

**Comment by williamcroberts** [comment]
> I got an error when I did test_tpm2_quote.sh

What do yo mean, "did"? The tests are designed to be run by make check, not manually. If you run them manually you're on your own (advanced).

> when I simply did tpm2_quote -k 0x81010004 -G sha1 -l 16,17,18 -m message.txt -s sign.txt, it did not > return any thing.

That seems like a bug, its failing somewhere and not printing a message.

> but, when I see echo $?, it printed 1 ( it means fail) and the sign.txt and message.txt did not created.
> how do i solve it?

You could throw it in a debugger and find where it's failing.

**Comment by williamcroberts** [comment]
A cursory glance throught the tool and the only place **I see** it failing silently would be on converting the -k option to a TPM handle. Your issue came right before we merged https://github.com/tpm2-software/tpm2-tools/pull/1239 (ESAPI port) which completely changed the behavior of the tools.

I also don't know if your on master or some 3.X release, so having those details, and all the steps you did to reproduce it on my end is super helpful.

Ill tag this as something to fix in 4.0 if you can give us reproduction steps, else well close it at release.

**Comment by williamcroberts** [comment]
Not reproducible.
