### ISSUE TITLE
No package 'tss2-esys' found

### ISSUE THREAD

**Issue by Richardds** [tpm2-software/tpm2-tools#1302]
Fix was merged into tpm2-tss

_Originally posted by @joshuagl in https://github.com/tpm2-software/tpm2-tools/issues/1291#issuecomment-460242249_

Now i keep gettings following error after `./configure`:

```
configure: error: Package requirements (tss2-esys) were not met:

No package 'tss2-esys' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSS2_ESYS_CFLAGS
and TSS2_ESYS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by joshuagl** [comment]
You may need to set `PKG_CONFIG_PATH` if your tpm2-tss is installed in a non-standard path for your distro, or indeed update to a version of tpm2-tss which provides the ESAPI (added in version 2.0)

**Comment by Richardds** [comment]
What should `PKG_CONFIG_PATH` variable contain? Could you please provide an example? I am on Ubuntu 18.10 (4.18.0-13-generic).

Thanks

**Comment by joshuagl** [comment]
Per the README help requests are better handled on the mailing list: https://lists.01.org/mailman/listinfo/tpm2

It's likely that your system's default install location isn't included in the default `PKG_CONFIG_PATH`s. You should find where tpm2-tss was installed to (possibly /usr/local/lib) and add the pkgconfig subdirectory of that location to PKG_CONFIG_PATH, i.e.

> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure

**Comment by iiiidddd** [comment]
I had the same problem in OpenSuSE because it has different names for the packages and libraries and pkg-config doesn't know about them for some reason 😕.

1. Find out package name

2. Find out library name
3.

**Comment by williamcroberts** [comment]
> @williamcroberts I think this should be part of the README.md of `tpm2-tools`, especially for people who want to use latest master of tpm2-tss OR run from source rather than packaging system
> 
> ```
> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure
> ```
> 
> I just ran into this and had to end up in this issue to be reminded about why my `pkgconfig` is not working as expected. I know it is silly when you do it every day, but we shall not assume people do this everyday and have this knowledge ;)

This is actually distro dependent since they configure what the default pkg-config paths are. You can actually check by doing:
`pkg-config --variable=pc_path pkg-config` and it shows what the configuration is. This is very much an autoconf/autotools/pkg-config mystery thing, I am OK with adding it, just submit a patch to the proper documentation you want it in.

**Comment by akashbeh** [comment]
Update: I was able to fix this error by 

sudo apt update

sudo apt install libtss2-dev tpm2-tools

./configure

But then I got: No package 'libqrencode' found

sudo apt install libqrencode4

Still ./configure with no PKG_CONFIG_PATH or the path of /usr/lib/x86_64-linux-gnu failed.

Turns out my computer (PureOS Librem 14) may only support TPM 1.2. Looking into other methods for TPM

**Comment by tomoveu** [comment]
TPM support in Librem14 seems present since 2018 @akashbeh , see here https://forums.puri.sm/t/librem-mini-pc-must-support-secure-boot-tpm-2-0-not-enabled/29673/4

TPM 1.2 is deprecated around 2016 and you do NOT have TPM 1.2. 
**Librem14 either has a TPM 2.0 or no TPM at all.**

You seem to have a compilation (software) problem. The easiest way to check for TPM 2.0 is to follow the steps from the librem forum above AND install the tpm2-tools packages not from source. Good luck
