### ISSUE TITLE
_FORTIFY_SOURCE requires compiling with optimization (-O)

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tools#1561]
Trying to build the latest master commit https://github.com/tpm2-software/tpm2-tools/commit/9381559b055b4b7e12a10aa4bcf65586f5571755 throws an error using the documented build process

Build process:

```sh
git clone https://github.com/tpm2-software/tpm2-tools.git && \
    cd tpm2-tools && git checkout master && \
    ./bootstrap && ./configure && \
    make -j$(nproc) && make install
```

Make throws the following error:

```text
  CC       tools/misc/tpm2_checkquote.o
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:25,
                 from tools/misc/tpm2_checkquote.c:3:
/usr/include/features.h:381:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:2522: tools/misc/tpm2_checkquote.o] Error 1
```

With commit https://github.com/tpm2-software/tpm2-tools/commit/f68e69b9, the original process works. 

Versions:

1. Fedora 29
2. tpm2-tss: 28143b43
3. gcc --version

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC)
```

**Comment by dnoliver** [comment]
Apparently, using `./configure --disable-hardening` makes the build pass in my setup. 

I am not sure if this "fixes" the problem, or generate a much worse one with non-hardened binaries. 

Any comments on this?

**Comment by joholl** [comment]
Per default, configure is called with hardening enabled. As a consequence, a bunch of gcc compiler flags are used, inluding `-D_FORTIFY_SOURCE=2` (see [configure.ac](https://github.com/tpm2-software/tpm2-tools/blob/master/configure.ac#L169)).

Since [this glibc commit](https://sourceware.org/git/?p=glibc.git;a=commit;f=include/features.h;h=05c2c9618f583ea4acd69b3fe5ae2a2922dd2ddc), the user is warned if optimization is not turnt on `-O`. We might want to add `-O` to the compiler flags when hardening is enabled.

@williamcroberts What do you think?

**Comment by diabonas** [comment]
Fortification needs optimisation enabled indeed. The default behaviour of [`AC_PROG_CC`](https://github.com/tpm2-software/tpm2-tools/blob/3535ed92281bf975c8b46ab07808480ef23ac96c/configure.ac#L8) is to [add `-O2` to `CFLAGS`](https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/C-Compiler.html), but this doesn't happen any more since [`AX_CHECK_ENABLE_DEBUG([info])`](https://github.com/tpm2-software/tpm2-tools/blob/3535ed92281bf975c8b46ab07808480ef23ac96c/configure.ac#L6) explicitly sets `CFLAGS="$CFLAGS -g"`. I concur with @joholl that we should enable optimisation during hardening and have prepared #1590.
