### ISSUE TITLE
Erase NV nonvolatile memory

### ISSUE THREAD

**Issue by MWalzDE** [tpm2-software/tpm2-tools#1596]
Hi guys, 
I am using tpm2-tools 3.1.3 with the linux 4.19 resource manager /dev/tpmrm0 on a hardware TPM. I did some tests and used tpm2_evictcontrol to store my own data in the TPM. While testing I cleared the TPM several times using tpm2_takeownership -c
Now tpm2_nvlist shows two entries:

0x1c00002:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 1177

0x1c0000a:
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 780

I tried to clear the NV memory with 

$ tpm2_nvrelease -x 0x01c00002
ERROR: Failed to release NV area at index 0x1c00002 (29360130).Error:0x184
ERROR: Unable to run tpm2_nvrelease
$ tpm2_nvrelease -x 0x01c00002 -a 0x40000001
ERROR: Failed to release NV area at index 0x1c00002 (29360130).Error:0x149
ERROR: Unable to run tpm2_nvrelease
$ tpm2_nvrelease -x 0x01c00002 -a 0x4000000C
ERROR: Failed to release NV area at index 0x1c00002 (29360130).Error:0x9a2
ERROR: Unable to run tpm2_nvrelease

It seems to me that I have lost the ability to release the NV indices when I did a reset on the hierarchies, did I? Is there a way to reset a TPM device to "factory default" or to force a complete erase? Thanks for your help!

Best regards,
Michael

**Comment by idesai** [comment]
@MWalzDE the problem I see is that the NV attributes chosen to define the NV Index. Particularly “platformcreate”. In that, when this attribute is set, the index can no longer be undefined with owner auth. Only platform auth can be used to undefine the NV index. I can imagine how this is going to be challenging to undefine the index in your case since it is on a hardware TPM unless you have access to the platform auth, But then again that is the very intent of using the “platform create” attribute when defining the NV index.

For questions like these, the mailing list is the correct avenue as documented in the README. And so closing this out in the issue tracker.
