### ISSUE TITLE
Error install tpm2-tools

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-tools#1605]
Requested 'tss2-esys >= 2.3.0' but version of tss2-esys is 2.2.3

How to fix?

**Comment by AndreasFuchsSIT** [comment]
tpm2-tss/master has 2.3.0-dev which is >= 2.3.0 which is also what is intended.
2.3.0-rc0 will arrive about the end of the week, just in time for the tool's 4.0

**Comment by roberto497** [comment]
I intend to use version 2.2.2 of tpm-tss because I already have a working example, but when I try to install a release of tpm-tools, some commands don't exist, like tpm2_clear, this command only works when I install via git clone, because does it occur?

**Comment by AndreasFuchsSIT** [comment]
tpm2-tools will come with a lot of major internal and external reworks; including different tools and parameters but also a new internal library.
So tpm2-tools 3.x goes with tpm2-tss 2.2.x and tpm2-tools 4.x goes with tpm2-tss 2.3.x

Due to the many changes it is also not trivial to backport tools from 4.x to 3.x but rather they'd have to be written from scratch.

For this and a lot of other benefits coming with 2.3 and 4.0 I'd recommend going that route in any case.

**Comment by AndreasFuchsSIT** [comment]
P.S. Also there may come a JSON marshalling library into existence in the future that this endevor could leverage on... But that would possibly require a little spec similar to libtss2-mu.h/so
