### ISSUE TITLE
Support python3 for tpm2-tools v4

### ISSUE THREAD

**Issue by nullr0ute** [tpm2-software/tpm2-tools#1708]
Python is used in a couple of places, primarily in the tests, but also in some of the configure checks for the build. With python2 going EOL at the end of this year and a lot of Linux distros actively moving to python3 as their default (or not shipping a /usr/bin/python binary) the tpm2-tools should detect and work with python3

**Comment by diabonas** [comment]
The scripts themselves are compatible with Python 3 already, I think this would be only a matter of changing all invocations of `python` to `python3`, since that should work on all recent major distributions. Probably this can wait until after Python 2 is EOL, since I believe most distributions still have `/usr/bin/python`, and we don't care whether it is a symlink to `python2` or `python3`.

**Comment by williamcroberts** [comment]
This is all being tested now and works with python3 and python2. The CI scripts are building on multiple distros each using a different flavor of python, see:
  - https://github.com/tpm2-software/tpm2-tools/commit/d08a4b2fd57bb764812f868950ee47778ac70d72
  - https://github.com/tpm2-software/tpm2-tools/commit/55f9be3a0c45bfe37dc09c64646e7ff39c454a89
  - https://github.com/tpm2-software/tpm2-tools/commit/44ec17ba2c6b69799ba9aba9a9c4c2a2ae8bf459
