### ISSUE TITLE
tpm2-tool can't execute normally on X86 target

### ISSUE THREAD

**Issue by kaloho** [tpm2-software/tpm2-tools#1722]
Hi all :
when i build tpm2 tool on PC Ubuntu 16.04, and it can execute,
then put it tools on the X86 target board, but can't execute normally.

All tpm2 command the same problem for example as below :
/bin/sh: ./tpm2_pcrread: not found

It is my configure environment :
./configure --enable-static

Can someone help me how to execute normally on X86 target?
the target doesn't have apt-get... etc.

thank you very much.

**Comment by williamcroberts** [comment]
Its probably because they are not on your PATH variable. That's how the shell finds stuff when you **don't specify an absolute or relative path**.

There are three ways to correct this:
1. Add the directory to PATH (see below for details)
2. `cd` to where the tools are and invoke them with a leading `./`, like: `./tpm2_getcap`.
3. Use absolute path, like `/foo/bar/tpm2_getcap`

Lets say you put the files in directory `/foo/bar`. You need to do:
```bash
export PATH="$PATH:/foo/bar"
```
If you have the `which` command, that will search path and give you the executable location. It's a good way to check that it's on `PATH`.
```bash
which tpm2_getcap
/foo/bar/tpm2_getcap
```
Per the readme, please ask questions on the mailing list:
https://lists.01.org/mailman/listinfo/tpm2

If you still cant solve your issue, ask there. Closing.

**Comment by kaloho** [comment]
Hi williamcroberts:

Thank you for your reply.
It still can't solve, i have mail to  **tpm2@lists.01.org** for console log,
hopefully you can take a look, thanks a lot.

**Comment by williamcroberts** [comment]
> Hi williamcroberts:
> 
> Thank you for your reply.
> It still can't solve, i have mail to **[tpm2@lists.01.org](mailto:tpm2@lists.01.org)** for console log,
> hopefully you can take a look, thanks a lot.

Responded via list
