### ISSUE TITLE
Consider providing a shared library of helper functions for building other TPM tools?

### ISSUE THREAD

**Issue by danc86** [tpm2-software/tpm2-tools#1738]
For our project we have built a program which performs a little sequence of TPM operations using some hardcoded constants and policy for our particular configuration. We reused a lot of the excellent code you have built for tpm2-tools. Essentially we have our own custom, product-specific TPM tool.

Currently we're building our program by just grabbing libcommon.a out of the tpm2-tools build process and then linking that into our program, but it's a bit messy.

Would you consider providing a shared library, say `libtpm2tools.so`, containing some of the reusable helper functions that are useful for building TPM-related tools externally?

**Comment by danc86** [comment]
I filed PR #1739 just as a conversation starter. It is the least invasive change to expose a useful shared library. There are some open questions though...

What are the set of symbols that should be exposed? The list of symbols I chose in PR #1739 is a bit arbitrary, this is the actual list we are linking against for our custom program:
```
tpm2_tcti_ldr_load
tpm2_tcti_ldr_unload
tpm2_policy_build
tpm2_policy_pcr_build
tpm_session_start_auth_with_params
tpm_session_auth_end
```
but that is still using version 2.2.x and there have been quite substantial API changes in tpm2-tools since then, and all those symbols don't exist anymore. That leads to the other important question...

What level of ABI stability should be offered? Ideally the library would have a proper soname version which is incremented whenever there are ABI-incompatible changes, and ideally that would happen as infrequently as possible. But if that's too burdensome, you could leave it with version 0.0.0 and explicitly not offer any ABI guarantees. That makes things a bit more difficult for downstream consumers but it is still better than the current situation (no shared library at all).

**Comment by martinezjavier** [comment]
@danc86 I'm not sure if this falls into the scope of the tpm2-tools project. Some of the goals for the projects are the following as far as I can tell:

* Provide a set of command line tools to easily interfact with a TPM2.
* Allow to quickly prototype solutions that involve a TPM2 using shell scripts.
* Have reference code on how to properly use the SAPI and ESAPI TCG APIs.

But providing a shared library will meant exposing an API that has to be maintained (right now the only contract was the tools names and options / arguments). This will make much harder to refactor the tpm2-tools internals, since some of that will be exposed as a library.

Most of the tools are really a wrapper around ESAPI nowadays and my understanding is that if you need a simpler / higher level API, then FAPI should be used.

@AndreasFuchsSIT @flihp what's your opinion on this?

**Comment by martinezjavier** [comment]
I see now that @williamcroberts already answered in PR #1739, saying something similar.
