### ISSUE TITLE
LOST hope after changing handlers from -H to -c

### ISSUE THREAD

**Issue by homepods** [tpm2-software/tpm2-tools#1749]
Guys,

After the recent update, I canot open my backup drives with 4tb of history

tpm2_unseal: invalid option -- 'H'
Keyfile could not be opened.
 
I trusted tpm to.be the only device to store the keyfile but now, after you radically changed the structure handles I cannot open my drive.

Tpm is the backupdevice no other ways to get the file 

On pcr7 just with sha1:7

How can I revert or change the initramfs which are signed and the key is in tpm???

How can I get my data back??

Why do you make radical changes in the structure??? 

Let me know a hack to.get my file from tpm.without access to initramfs or kernel

**Comment by joholl** [comment]
As noted in the [REALEASE.md](https://github.com/tpm2-software/tpm2-tools/blob/21e3b11fa312fddb54a54a6fc154625eedac92ab/RELEASE.md#L4), we follow [semantic versioning](https://semver.org/). This means any API change will result in the major version to be incremented - like with [tpm2-tools 4.0](https://github.com/tpm2-software/tpm2-tools/releases/tag/4.0) which was released 2 weeks ago. Obviously the tools 4.0 are not backwards compatible, hence your problem.

The easiest option is downgrading your tpm2-tools to the version you had installed prior to the update.

However, the tools 4.0 should still capable of what they could do before, only the way you call them changed. So if you want to stick with version 4.0 have look into the [changelog](https://github.com/tpm2-software/tpm2-tools/releases/tag/4.0).

As for the specific problem with `tpm2_unseal`: the parameter `-H` was basically replaced by `-c` in [this commit](https://github.com/tpm2-software/tpm2-tools/commit/75af2b89333ce1d573eace2de0323b7908895284). `-c` accepts either the path to a key context file or a handle, e.g. `0x81010001`. For more infos, see the man pages.

**Comment by homepods** [comment]
I have seen the documentation but let me be clear here.

By no means I can revert neither because I dont have access to disks.  

Changing haldlers is like changing keys. I cannot imagine the work it is done, but the software architecture should follow a consistent line of development. 
Especially with hardware. You know why? Because if you change the keys you lock yourself out.

Imagine if I go to your house and I change your yale. By no means if you have the keys they dont fit in.

Same here. 

Ive tried every hack but I cannot unseal it. 
Let me know how to force or emergency unseal it. 

After changing handlers is there a period of transition?

I cannot imagine how I can use this again. Ive lost everything. I feel so depressed.


Help me!

**Comment by idesai** [comment]
4.0 option renaming were done to bring consistency in option names across all the tools. Yes, there is a period of transition where release candidates are issued prior to any (major/minor/bugfix) releases and api compatibility follows the https://semver.org/ model like @joholl indicated.

@homepods to address your specific issue, can you please share more details on your setup on the mailing list at https://lists.01.org/mailman/listinfo/tpm2.

PS: As for emergency unsealing your data off the TPM; you indicated in your setup you use PCR7 which is commonly used to extend secure boot policy and so mostly remains fixed. Is it then not possible to boot from another media and unseal your secret? @martinezjavier how is it setup in clevis?

**Comment by homepods** [comment]
@idesai ive tried every hack. I cant unseal it. After changing the pk, pcr7 changes to. It should remain unchanged as pcr7 is a manufacturer information slot including info on secure boot. But it isnt Boolean therefore I canot unseal. 

I have tried to inject the kernel to change from -H to -c and so forth but cant pass unhiden, and without there is a magic error.

There should be an emergency unseal untill this repo gets a clear roadmap so that handlers are not changed, but improved so you can use them 

Anyone can help me fix this?

I really need your help

**Comment by idesai** [comment]
@homepods based on what you said, the reason that you cannot unseal any more is due to the fact that the PCR7 policy is no longer valid due to changes to PCR7. And so even if the option names were to remain the same you would have still ended up in this situation. If anything the fact that the unseal operation failed because your system software state changed as reflected by PCR7 is exactly the type of attacks it was meant to thwart.

Given that system software state changes is an intended outcome it should be factored in the backup and recovery of the sealed data. For example Bitlocker in Windows, besides TPM as the protector for the disk encryption key, the key is additionally wrapped and saved to a media like USB memory stick.

However, If TPM is the only intended key protector then a fail safe system design (or emergency unsealing) should consider flexible policies like [policyauthorize](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyauthorize.1.md) or also [policyOR](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyor.1.md), or also [policyauthorizenv](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyauthorizenv.1.md), etc.

Assuming you haven't cleared the TPM, The only hack in your case is to revert the PCR7 values by reverting the PK to satisfy the fixed PCR policy to be able to unseal.

**Comment by homepods** [comment]
I don't think you understand the problem. You guys changed **-H / -L -> -c -p pcr:**  - the key was stored in TPM
useal didn't work -> no access to the key.
All boot files were signed, every change in the bits order, would result in policy violation.
With access to booloader and the key still inside, I have tried to inject the archived kernel, to change the handlers, but I could not match the bits (i've mananged to change **-H and -L**) but **pcr:** was an extra 4 bits. I've tried to delete other text in commented text, but with no scucess.
Bootloader not passing, indicating magic error.

After trying all of this, I've tried to change the PK to acess bootloader so I can retrieve the key from the shell. It didn't work either, nor any other emergency shell.

So, I've quit. I've lost 4tb of data, recent data.

If changes are made to handlers, they should be consistent in lenght at least.

**Comment by diabonas** [comment]
> If changes are made to handlers, they should be consistent in lenght at least.

That wouldn't help, since every change to the signed file, even if keeping the length consistent, will result in an invalid signature. As @joholl mentioned we use semantic versioning, so any major version bump indicates backwards-incompatible changes. It is essential to test the new version before upgrading, or at least to keep a backup of the old, working initramfs. Even better would be a backup of the sealed keyfile or an additional "emergency" decryption password.

> After trying all of this, I've tried to change the PK to acess bootloader so I can retrieve the key from the shell. It didn't work either, nor any other emergency shell.

The platform key is measured to PCR 7, so any change to the PK results in a different PCR value, which is why unsealing fails. You have the following options, ordered loosely by feasibility:
- Try to obtain a keyfile/passphrase for the LUKS partition: did you use a passphrase to access the encrypted partition before moving to a TPM-based keyfile? If so, do you still know this passphrase and do you have a backup of the LUKS header from this time?
- Try to obtain an old, working initramfs with tpm2-tools 3.1: do you have a backup of the old initramfs that you can exchange for the new, broken one? If not, you can try restoring the old deleted initramfs from your harddrive using data recovery software or a professional data recovery specialist. You need to restore the previously used PK before using the old initramfs.
- Try to get access to a recovery shell in your current, broken initramfs: whether such a shell is included and under what conditions it can be accessed depends on your initramfs generator and configuration. You will also need to restore the PK you used to seal the keyfile for this to work.
- Talk to a professional data recovery specialist to explore other options.

All of these suggestions are out of scope for this project though.
