### ISSUE TITLE
Removed 4.X branch

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tools#1768]
I noticed the 4.X branch, which [used to point to the same commit as the 4.0 tag](https://travis-ci.org/tpm2-software/tpm2-tools/builds/582831806), got removed. Was this done on purpose? For tpm2-tss-engine, we would like to [depend on the latest stable release series](https://github.com/tpm2-software/tpm2-tss-engine/pull/142), so having a stable branch to track would be nice. As an alternative, we can build from the 4.0 tag of course, but that needs an update every time a new tpm2-tools release is made.

**Comment by AndreasFuchsSIT** [comment]
+1

**Comment by idesai** [comment]
Yes, it was purported. We intend to create the branch soon as a bug fix would be necessitated or if new features are going to be added. And so by that extension, the 4.0 tag continues to be the stable version.

**Comment by williamcroberts** [comment]
Yeah we don't need the 4.X branch, since it was just going to be master. We would have had to constantly pull master into 4.X (which would be all fast forwards) or abandon master and make 4.X the primary dev branch.

For minor releases, which I just did for 4.0.1, I created a branch off the tag. We can always go back in time. For now track master, we will be providing backwards compatible changes, so we should never really go to 5.X (at least for now).
