### ISSUE TITLE
Fails to build if tpm2-tss is compiled with --disable-tcti-mssim

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tools#1851]
tpm2-tools fails to build if tpm2-tss is compiled with --disable-tcti-mssim.

Here's my output:

```
checking for TSS2_ESYS... no
configure: error: Package requirements (tss2-esys >= 2.3.0) were not met:

Package 'tss2-tcti-mssim', required by 'tss2-esys', not found
```

**Comment by diabonas** [comment]
That's a bug for [tpm2-tss](https://github.com/tpm2-software/tpm2-tss) (CC @AndreasFuchsSIT), we should remove `tss2-tcti-device` and `tss2-tcti-mssim` from `Requires.private` in [`lib/tss2-esys.pc.in`](https://github.com/tpm2-software/tpm2-tss/blob/master/lib/tss2-esys.pc.in) since https://github.com/tpm2-software/tpm2-tss/pull/1457 and the switch to tss2-tctildr.

**Comment by AndreasFuchsSIT** [comment]
Were you trying to build a static version of the tools ?
Because Reuires.private should only be evaluated then, right ?
