### ISSUE TITLE
tpm2_listpersistent gone. . . . . . and now what. . . . ?

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tools#1853]
I see that "**_tpm2_listpersistent_**" is no longer a part of tpm2_tools.

I figured that I should use "tpm2_getcap" instead, and as I found the manual entry for tpm2_getcap very confusing, I tried every option in a script like this:

```
#!/bin/sh
tpm2_getcap
tpm2_getcap algorithms
tpm2_getcap commands
tpm2_getcap ecc-curves
tpm2_getcap handles-loaded-session
tpm2_getcap handles-nv-index
tpm2_getcap handles-pcr
tpm2_getcap handles-permanent
tpm2_getcap handles-persistent
tpm2_getcap handles-saved-session
tpm2_getcap handles-transient
tpm2_getcap pcrs
tpm2_getcap properties-fixed
tpm2_getcap properties-variable
```

I looked through the output line by line but I still couldn't see (or understand) if I had persistent objects or what their names were.

The problem I'm having is that I try to load a key into the TPM2 chip, and I'm getting this error:

```
tpm2_createprimary -T device:/dev/tpm0 -c primary.ctx
tpm2_create -T device:/dev/tpm0 -C primary.ctx -Gaes128 -u key.pub -r key.priv
tpm2_load -T device:/dev/tpm0 -C primary.ctx -u key.pub -r key.priv -c key.ctx
WARNING:esys:src/tss2-esys/api/Esys_Load.c:320:Esys_Load_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x00000902)
ERROR: Eys_Load(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Unable to run tpm2_load
```

Presumably the problem here is that I need to clear all the keys out of my TPM2 chip. I tried booting into the BIOS to do this, and I tried to, but it had no effect. Still getting the error "out of memory for object contexts".

So I did some web searching and I saw people use "tpm2_listpersistent" along with "tpm2_evictcontrol" in order to clear out the key. I can't copy what these people did because I don't have "tpm2_listpersistent".

Anyone know how I can factory-reset my TPM2 chip?

**Comment by idesai** [comment]
After tpm2_create, issue tpm2_flushcontext -t and then try load.
By factory reset, you mean tpm2_clear?

PS: Please direct how to questions to the mailing list. Thanks.

**Comment by DaVolfman** [comment]
If you have memory issues loading a context it is unlikely data in the persistent objects or NV regions is your problem.  You probably have too much temporary state hence the above suggestion to use tpm2_flushcontext.  You can prevent this by using a resource manager, if you're using context files rather than depending on transient objects sticking around even the kernel resource manager at /dev/tpmrm0 would probably work and the ABRMD is nice and automatic.

If you still want to clear persistent objects the listpersistent and nvlist commands have been removed as redundant.
To list persistent objects use "tpm2_getcap handles-persistent"  if you want detailed information use tpm2_readpublic on individual handles.  To list nv indices now use "tpm2_getcap handles-nv-index" and tpm2_nvreadpublic if you want detailed info.

**Comment by williamcroberts** [comment]
@jhealyt You're not using a resource manager, and you have too many objects loaded up, hence the return code. You need to manually manage the memory of the TPM, or use a resource manager. Many kernels have /dev/tpmrm0 to use (Note the rm for resource manager). I think its kernel version 4.12 and above will have this. You can also use tpm2-abrmd a userspace resource manager.

to list persistent objects, just use `tpm2_getcap handles-persistent` But thats only one issue, you are using all the transient object memory (tpm2_load loads to volatile transient memory). If you look at the variable-properties:
```sh
tpm2_getcap properties-variable | grep TPM2_PT_HR_TRANSIENT_AVAIL
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
```

You can see how many transient slots you have, and you can use `tpm2_flushcontext` to evict it.

Your best bet is to use a resource manager.
