### ISSUE TITLE
Endorsement Key created with tpm2_createek cannot be used with tpm2_activatecredential

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tools#1883]
The following script works

```bash
echo "Enrolling with Endorsement Key"

# Clear the TPM
tpm2_clear

# Create Endorsement Key
tpm2_createprimary -c ek.ctx -C e
tpm2_readpublic -c ek.ctx -o ek.pub > ek.yaml
cat ek.yaml | grep '^name:' | awk '{ print $2 }' > ek.name

# Generate the nonce and credential for challenge
openssl rand -hex 6 > nonce.plain
tpm2_makecredential -T none -e ek.pub -s nonce.plain -n $(cat ek.name) -o nonce.encrypted

# Decrypt nonce with Endorsement Key
tpm2_activatecredential -c ek.ctx -C ek.ctx -i nonce.encrypted -o nonce.decrypted

# Validate nonce
diff nonce.decrypted nonce.plain
```

But this script fails:

```bash
echo "Enrolling with Endorsement Key"

# Clear the TPM
tpm2_clear

# Create Endorsement Key
tpm2_createek -c ek.ctx
tpm2_readpublic -c ek.ctx -o ek.pub > ek.yaml
cat ek.yaml | grep '^name:' | awk '{ print $2 }' > ek.name

# Generate the nonce and credential for challenge
openssl rand -hex 6 > nonce.plain
tpm2_makecredential -T none -e ek.pub -s nonce.plain -n $(cat ek.name) -o nonce.encrypted

# Decrypt nonce with Endorsement Key
tpm2_activatecredential -c ek.ctx -C ek.ctx -i nonce.encrypted -o nonce.decrypted

# Validate nonce
diff nonce.decrypted nonce.plain
```

The output of the test script:

```bash
+ export TPM2TOOLS_TCTI=device:/dev/tpmrm0
+ TPM2TOOLS_TCTI=device:/dev/tpmrm0
+ case "${1-}" in
+ enroll_with_ek
+ echo 'Enrolling with Endorsement Key'
Enrolling with Endorsement Key
+ tpm2_clear
+ tpm2_createek -c ek.ctx
+ tpm2_readpublic -c ek.ctx -o ek.pub
+ cat ek.yaml
+ grep '^name:'
+ awk '{ print $2 }'
+ openssl rand -hex 6
++ cat ek.name
+ tpm2_makecredential -T none -e ek.pub -s nonce.plain -n 000bdcd6527a19253292494864d9fce3ad66da41acdbe240d35ed94d46003eac6dca -o nonce.encrypted
+ tpm2_activatecredential -c ek.ctx -C ek.ctx -i nonce.encrypted -o nonce.decrypted

WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:314:Esys_ActivateCredential_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x00000124) 
ERROR: Esys_ActivateCredential(0x124) - tpm:error(2.0): authorization handle is not correct for command
ERROR: Unable to run tpm2_activatecredential
```

Is the output of `tpm2_createek` expected to work with `tpm2_makecredential` and `tpm2_activatecredential`?

**Comment by idesai** [comment]
@dnoliver are you following the [attestation-example](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/attestation.sh)?

**Comment by dnoliver** [comment]
That worked with the EK + AK example I posted before. I have problems to make this work with EK only.

I tried the following:

```text
cho "Enrolling with Endorsement Key"

  # Clear the TPM
  tpm2_clear

  # Create Endorsement Key
  tpm2_createek -c ek.ctx
  tpm2_readpublic -c ek.ctx -o ek.pub > ek.yaml
  cat ek.yaml | grep '^name:' | awk '{ print $2 }' > ek.name

  # Generate the nonce and credential for challenge
  openssl rand -hex 6 > nonce.plain
  tpm2_makecredential -T none -e ek.pub -s nonce.plain -n $(cat ek.name) -o nonce.encrypted

  # Decrypt nonce with Endorsement Key
  tpm2_startauthsession --policy-session -S session.ctx
  TPM2_RH_ENDORSEMENT=0x4000000B
  tpm2_policysecret -S session.ctx -c ${TPM2_RH_ENDORSEMENT}
  tpm2_activatecredential -c ek.ctx -C ek.ctx -i nonce.encrypted -o nonce.decrypted -P "session:session.ctx"
  tpm2_flushcontext session.ctx

  # Validate nonce
  diff nonce.decrypted nonce.plain
```
But got 

```bash
[root@fedora-server-1 test1]# bash enrollment.sh ek
+ export TPM2TOOLS_TCTI=device:/dev/tpmrm0
+ TPM2TOOLS_TCTI=device:/dev/tpmrm0
+ case "${1-}" in
+ enroll_with_ek
+ echo 'Enrolling with Endorsement Key'
Enrolling with Endorsement Key
+ tpm2_clear
+ tpm2_createek -c ek.ctx
+ tpm2_readpublic -c ek.ctx -o ek.pub
+ cat ek.yaml
+ grep '^name:'
+ awk '{ print $2 }'
+ openssl rand -hex 6
++ cat ek.name
+ tpm2_makecredential -T none -e ek.pub -s nonce.plain -n 000bdcd6527a19253292494864d9fce3ad66da41acdbe240d35ed94d46003eac6dca -o nonce.encrypted
+ tpm2_startauthsession --policy-session -S session.ctx
+ TPM2_RH_ENDORSEMENT=0x4000000B
+ tpm2_policysecret -S session.ctx -c 0x4000000B
837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa
+ tpm2_activatecredential -c ek.ctx -C ek.ctx -i nonce.encrypted -o nonce.decrypted -P session:session.ctx
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:314:Esys_ActivateCredential_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x00000124) 
ERROR: Esys_ActivateCredential(0x124) - tpm:error(2.0): authorization handle is not correct for command
ERROR: Unable to run tpm2_activatecredential
```

**Comment by idesai** [comment]
@dnoliver  Trying to understand the point of your exercise. The reasoning for credential activation of a child key is to protect the anonymity of the keyhandle which is the endorsement key in your case. But you are making both to be the same, then why use credential activation? So I believe the key attributes do not allow for it.

**Comment by dnoliver** [comment]
(sorry for late response!)

The intention is to gave a "reference implementation" on how to verify the identity of a given host based on its TPM keys. There were 3 approaches explored

1. EK only (this one)
2. EK + SRK (similar to https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/tpm-key-attestation)
3. EK + AK (similar to the one used by Keylime)

2 and 3 were discussed in the mail list, and there are example implementations here https://gist.github.com/dnoliver/04364e72d8b81368f72ad4e6896f688d

The EK only approach consisted on a client-server mechanism, where the server only knows the EK public part, and presents a challenge to the client. The challenge is a nonce generated in the server, encrypted with the EK public part, that needs to be decrypted by the client to prove that it is has access to the EK private part. 

Problem is that the EK is a restricted encryption key, so the only way I could replicate that flow was to use the Make Credential and Activate Credential commands (used for EK + SRK and EK + AIK approaches). This worked with the pseudo-ek key created with the `tpm2_createprimary -C e` command, but I was not able to make it work with a real EK key created with `tpm2_createek`, because of that authorization problem described.

I am not sure if this is the correct approach and usage of Make/Activate Credential, it was just my approach of solving this problem (and get it reviewed in the in this and related threads https://ml01.01.org/hyperkitty/list/tpm2@lists.01.org/thread/TKGG3OP5KU5VSRHNKAKLLI4VE42ESGVI/)

If this is an incorrect usage of the EK, I will have to look for another way of doing it :)

**Comment by nicowilliams** [comment]
@idesai I have the same question as @dnoliver and I can explain my use-case as follows:

 - we want the attestation server to store only ciphertext(s) that only the client can decrypt, with the attestation server unable to decrypt those ciphertexts itself.

To achieve that the most obvious thing to do is to store the `credentialBlob` output of `TPM2_MakeCredential()` and keep sending it to the client every time it attests.  Except that normally one calls `TPM2_MakeCredential(EKpub, AKname, secret)` with an `AKname` naming an ephemeral `AK` (i.e., it has `stClear`), so... one cannot store the `credentialBlob` output and reuse it across client reboots.  So that idea is out.

The next obvious idea is to store the output of `TPM2_MakeCredential(EKpub, EKname, secret)`, and on the client side correspondingly call `TPM2_ActivateCredential(EK, EK, credentialBlob)` to recover the `secret`.  This, however, neither @dnoliver nor @osresearch nor I know how to do.  See @dnoliver's shell transcript above and mine below that I hope illustrates the issue more clearly.

@osresearch came up with a different approach: store the output of `TPM2_Duplicate(EKpub, TK)` where `TK` is a locally generated RSA "transport key", then any secrets can be encrypted to the `TKpub` and sent alongside the duplicated key.  The client imports and loads the duplicated key, and decrypts the ciphertext to recover the secret(s).  Both, this and the approach @dnoliver was asking about use the `EK`, but the difference is that `TPM2_Import()` requires only `USER` role to use the `EK` to import the key duplicated to its `EKpub`, while `TPM2_ActivateCredential()` requires `ADMIN` role to use the `activateHandle` (typically the `AK`).  So that's the difference: `USER` vs `ADMIN` role for the `EK`.

(I think another approach would be to have the client generate an `AK` that does not have `stClear` and enroll its name so that we can then store `TPM2_MakeCredential(EKpub, longterm_AKname, secret)`'s output.  This is strictly more complex than the `TK` approach, so it's not worth considering any further.)

The workaround that @osresearch came up with works fine, but it seems a bit silly to have to do that.  The reason we can't get `TPM2_ActivateCredential(EK, EK, credentialBlob)` to work is that the `activateHandle` argument of `TPM2_ActivateCredential()` requires `ADMIN` role authorization, and we don't know how to meet that policy.

What we really want to know is just that: how to meet the `EK`'s `ADMIN` role authorization.

Motivation for wanting to know that is mostly a) curiosity, b) simplification / optimization (not having to generate, duplicate, import, load, use a `TK`) of the attestation protocol we're designing and implementing.

(I've separately been asking @kgoldman.)

```
# tpm2 createek --ek-context ek.ctx --public ek.pub
# tpm2 flushcontext -t; tpm2 flushcontext -s;
# authpolicy=$(tpm2 readpublic --object-context ek.ctx|grep '^authorization policy:'|cut -d' ' -f3)
# echo $authpolicy
837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa
# tpm2 flushcontext -t; tpm2 flushcontext -s; tpm2 startauthsession --session session.ctx --policy-session
# actual_authpolicy=$(tpm2 policysecret --session session.ctx --object-context endorsement)
# [[ $authpolicy = $actual_authpolicy ]] && echo AUTH POLICY MATCHES
AUTH POLICY MATCHES
# tpm2 activatecredential --credentialedkey-context ek.ctx --credentialkey-context ek.ctx --credentialkey-auth session:session.ctx --credential-blob cipher.bin --certinfo-data secret.txt
WARN: Will use the same object as the credential and credentialed objects
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:321:Esys_ActivateCredential_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x00000a8b)
ERROR: Esys_ActivateCredential(0xA8B) - tpm:session(2):the handle is not correct for the use
ERROR: Unable to run activatecredential
#
```

As you can see we have the correct auth policy in the session, and yet it's not enough.

Section 19.2 of the TCG TPM 2.0 library part 1 (Architecture) says:

> ADMIN–the  object  Administrator  controls  the  certification  of  an  object  (TPM2_Certify()and TPM2_ActivateCredential())     and     controls     changing     of     the authValueof     an     object (TPM2_ObjectChangeAuth()).  When  an  action  requires  ADMIN  role  authorization,  that  authorization may  be  provided  using  the authValueof  the  object  if  the adminWithPolicyattribute  of  the  object  is CLEAR. As with USER role authorization, ADMIN role may always be provided with a policy session as long as the policy session satisfies the authPolicyof the object.

The `EK` does have `adminWithPolicyattribute`, and the policy is the empty policy, and as you can see we're meeting that.  So... what's missing?

**Comment by nicowilliams** [comment]
@kgoldman tells me that indeed, it is not possible to use `TPM2_ActivateCredential(EK, EK, credentialBlob)`.

**Comment by kgold2** [comment]
Almost.  I think it is not possible with the current (low range) EK template, but it may be possible with the high range EK.  I have not tested it.
