### ISSUE TITLE
rsa exponent set to 0, displayed as zero, only to be changed later?

### ISSUE THREAD

**Issue by rowanmoul** [tpm2-software/tpm2-tools#1919]
Is there a reason to explicitly set the exponent to 0 here?
https://github.com/tpm2-software/tpm2-tools/blob/c375bb10f7e9b23e7aa74fcaf372342775060228/lib/tpm2_alg_util.c#L283-L288

Only to change it to `0x10001` here?
https://github.com/tpm2-software/tpm2-tools/blob/c375bb10f7e9b23e7aa74fcaf372342775060228/lib/tpm2_convert.c#L78-L81

Initially setting it to zero appears to have the downside that tools like tpm2_createprimary print out this upon completion:
```
type:
  value: rsa
  raw: 0x01
exponent: 0x0
bits: 2048
```
Seeing a zero exponent is a bit concerning at first (though it is reasonable to assume it's not actually zero).

**Comment by williamcroberts** [comment]
in `handle_rsa` we set it to 0 to initialize the struct member to something. We don't assume the caller has properly initialized the struct. We just pick 0 since it's the default in the TPM. We could set it 65536, but that's what it ends up as anyways. Perhaps in later TPM revisions, 0 will mean a different default prime.

In convert, we have to assume that the TPM can return us 0. Perhaps we didn't create the object, and even if we set it to 65536 in `handle_rsa`, old objects would still be 0. OpenSSL doesn't understand the 0 exponent to mean 65536, so we just set it there.

I agree that seeing a 0 exponent could be scary, since the TPM is doing something else. So I will create a PR to update the output.
