### ISSUE TITLE
Integration test scripts - inconsistent perms 

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tools#2003]
Some have 644 and some 755:
-rwxr-xr-x. test/integration/tests/abrmd_extended-sessions.sh
-rw-r--r--. test/integration/tests/abrmd_nvundefinespecial.sh
Change all to 755.

**Comment by williamcroberts** [comment]
We should probably change all to 644, because they are always executed by the test framework with an explicit call to bash <script>. However, we do have the shebang at the top of each one IIRC. Which would indicate we expect it to be run standalone, which is not really the case.

Either 755 everything, or drop the shebang and 644 everything.
