### ISSUE TITLE
no tpm2_takeownership

### ISSUE THREAD

**Issue by nimbius** [tpm2-software/tpm2-tools#2012]
tpm2_takeownership doesnt appear after building the latest source.

**Comment by idesai** [comment]
[tpm2_changeauth](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_changeauth.1.md)

**Comment by williamcroberts** [comment]
By design, tpm2_takeownership did two things:
with -c it ran tpm2_startup -c
With password options, changed passwords for hiearchy: tpm2_changeauth will do that.

See the changelog, where you can just grep for tool names and see a high level synopsis of what changed:
 - https://github.com/tpm2-software/tpm2-tools/blob/master/doc/CHANGELOG.md
