### ISSUE TITLE
tpm2_checkquote: only handles PEM formatted files

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2049]
`tpm2_createak` defaults to writing out in TSS binary format, but `tpm2_checkquote` will only work with PEM formatted keys. Is there a way to convert between these formats or should the default be changed so that they work together?

**Comment by osresearch** [comment]
As a hack, extract the modulus from the TPMT file (which is used for the sha256sum to create the name for `tmp2_makecredential`), wrap a DER header around it and the default exponent, then use openssl to convert that to PEM:

```
        ( \
                echo 30820122300d06092a864886f70d0101 | hex2bin ; \
                echo 0105000382010f003082010a0282010100 | hex2bin ; \
                tail -c 256 "$DIR/ak.pub" ; \
                echo 0203010001 | hex2bin ; \
        ) | openssl rsa \
                -pubin \
                -inform "DER" \
                -outform "PEM" \
                -out "$DIR/ak.pem" \
        || die "$DIR/ak.pub: unable to convert to ak.pem"
```

As they say in the infomercials, _There has to be a better way!_

**Comment by williamcroberts** [comment]
tpm2_readpublic will read the loaded AK and can output a pem public key.

However, I see two things:
  - tpm2_format should be able to take a public TPM2B_PUBLIC or TPMT_PUBLIC and output a pem file
  - tpm2_checkquote should be able to take the TSS blob

**Comment by osresearch** [comment]
That works on the client, but `tpm2_readpublic` doesn't work on the remote attestation server.

It seems that the best choice is for the client to send the TPMT format to the server (and `tpm2_checkquote` updated to be able to handle it) so that the server can then hash the entire `TPM2B_PUBLIC` structure to generate the AK name for `tpm2_makecredential`; otherwise the server doesn't know how to associate the AK with the name and would have to trust that the client provided the correct one.

**Comment by williamcroberts** [comment]
Yeah I agree, i'm just trying to provide you options. You could send out the public in PEM as well for now.

**Comment by williamcroberts** [comment]
So the attestation key is under the Endorsement Key. You verify the Endorsement Key to know that your talking to a genuine TPM. Step 1 of section 9.5.3 of https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf. I would imagine it would be signing some noce as the challenge response protocol.

For step 2, platform certs, I am not sure on that one.

For step three, you use tpm2_certify. You can send it a nonce, in the unique data and gives back a signed attestation saying, hey I have this key loaded. The attestation data it signs, I had to go dig in the simulator for, its a TPM2_ST_ATTEST_CERTIFY, which is a union and creates the TPMS_CERTIFY_INFO data. It's the name and the qualified name, serialized via libmu's Tss2_MU_TPMS_ATTEST_Marshal and then adds the qualifyinf data (nonce) to that, so its:

```C
	    TPMI_ALG_HASH           hashAlg;
	    // Compute hash
	    hashAlg = scheme->details.any.hashAlg;
	    // need to set the receive buffer to get something put in it
	    digest.t.size = sizeof(digest.t.buffer);
	    digest.t.size = CryptHashBlock(hashAlg, attest->t.size,
					   attest->t.attestationData,
					   digest.t.size, digest.t.buffer);
	    // If there is qualifying data, need to rehash the data
	    // hash(qualifyingData || hash(attestationData))
	    if(qualifyingData->t.size != 0)
		{
		    CryptHashStart(&hashState, hashAlg);
		    CryptDigestUpdate2B(&hashState, &qualifyingData->b);
		    CryptDigestUpdate2B(&hashState, &digest.b);
		    CryptHashEnd2B(&hashState, &digest.b);
		}
	    // Sign the hash. A TPM_RC_VALUE, TPM_RC_SCHEME, or
	    // TPM_RC_ATTRIBUTES error may be returned at this point
	    result = CryptSign(signKey, scheme, &digest, signature);
	    // Since the clock is used in an attestation, the state in NV is no longer
	    // "orderly" with respect to the data in RAM if the signature is valid
```

So that you would verify that on the attesting side by verifying the digest of the marshalled qualification data of expected qualified name, name and nonce.

Currently tpm2_createak only provides the name, but you'll need the qualified name as well. The qualified name is the name of it, and it's ancestors to the root. So the qualified name gives you validity that it's under the EK if you can use the name of the EK.

**Comment by williamcroberts** [comment]
The only way to get the qualified name is via readpublic, because the object has to be loaded in the hierarchy. I can add this to tpm2_createak output. We could output the qualified name by getting the TPM2B_CREATION_DATA from TPM2_Create and generating the qualified name.

**Comment by williamcroberts** [comment]
So now that I have a better grasp on this part of the spec, let me try and distill this, and understand that this is new for me, so I could be missing something or getting it wrong.

The EK is known at provision time. The manufacturer sets the Endorsement Primary Seed (EPS), so when you call tpm2_createek, you should get the key the manufacturer expects. This key is the same across ALL TPMS WITH THAT EPS. An attesting party can use this to verify that you're talking to a genuine TPM. This is Step 1. But since everyone shares the eps, thats all you know. You don't know the specific TPM.

The next step is creating the AK. The AK can be created and a certificate as well, tied to the attestation CA. This will create a chain that the AK is indeed good. This is step 2. This will also be the key that is unique to that particular client.

Then you can vouch for the attestation key using tpm2_certify, and prove that attestation key is in the TPM. Now you know its a genuine TPM and specific TPM. You can get quotes, and you would know exactly what to expect. Perhaps the client is running software X, so the PCR values from quote should be XXX.

**Comment by williamcroberts** [comment]
FYI I added qualified name output to tpm2_createak and tpm2_readpublic:
  - https://github.com/tpm2-software/tpm2-tools/pull/2052

**Comment by osresearch** [comment]
Wait, what the what? That seems incredibly bad.

Having a shared EK between TPMs means that an attacker only has to decap one to have a class break against that model or family, and since it is burned into hardware there isn't a way to patch it in all of the affected deployed systems.

**Comment by williamcroberts** [comment]
My comment is wrong, very wrong. The EPS is fixed to the TPM, but unique per TPM. The manufactures CA issues the EK cert. So I guess you do know what TPM your talking to. Not sure where my head was at when I made that comment.

**Comment by osresearch** [comment]
Whew... Glad to hear it was just a misinterpretation of the spec.  It's not totally out of the question -- Intel has a group signature scheme for SGX called EPID that has a goal of proving that you're in a real SGX enclave without the server being able to tell which CPU serial number it is, although it suffered from side-channels and is really over complicated.

![image](https://user-images.githubusercontent.com/3068843/82740771-2e6a1180-9d4c-11ea-981a-d5fe48ea2e46.png)

**Comment by williamcroberts** [comment]
But I got off topic, I think I read all your bugs and just confused them on one ticket, my apologies for that. 

To get back to this ticket, specifically, tpm2_checkquote. So yeah, tpm2_checkquote does not verify that the qname of the signing key matches. The attestation data will have the qname, along with some other details like time and reset count, and the quote info. So you would need to know what the qname of the key is.

qname is only obtainable from loaded keys, because the tools don't know the EPS or any hiearchy seed. To generate the qname for the EK:
`NameHashAlg(EPS || EKName)`

In theory the manufacturer would know the qname, I don't know if they embed this in any cert, you may want to see if an asn1 dump shows anything. But if anything signed by the EK validates against the EK Cert, that qname is fine, since the key material generated in tpm2_createprimary is tied to the EPS.

So the TL;DR is, name won't help, you don' t qname either, and qname is implied if the EK validates.

Does this make sense?
