### ISSUE TITLE
tpm2_makecredential: validating that ak.name matches ak.pem?

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2050]
When checking a quote with `tpm2_checkquote` it is necessary to use a PEM formatted public attestation key (#2049), but `tpm2_makecredential` requires a hex formatted key name. `tpm2_createak` will write out a file (in binary, so it has to be converted to hex), but how does the remote attestation server validate that the name corresponds to the public key?

For simplicity it would be easiest if `tpm2_makecredential` would take the `ak.pem` file as input instead, so that there are fewer things that have to be cross-validated during attestation (similar to #2047).

**Comment by osresearch** [comment]
It looks like the name is created by sha256sum of the `tpm2_createak --format tpmt` output, plus `0x00 0x0b` on the front of it, so perhaps the client can send the tpmt file to the server as the canonical version. This would require that either adding tpmt support to `tpm2_checkquote` or a tool to convert a tpmt formatted attestion key to PEM.

**Comment by williamcroberts** [comment]
While I digest this and look into it, the 0x000b is the name algorithm, so thats sha256. Its the sh256 of the TPMT_PUBLIC with the algorithm UINT16 prepended.

**Comment by williamcroberts** [comment]
1. tpm2_checkqoute should be able to take a public template, just for interoperability.
2. tpm2_makecredential needs either:
  - template file (nothing more)
  - pem + name + symmetric details (scheme)
3. If you need to validate a key, either validate against it's cert or use tpm2_certify and validate the attestation response signature to its cert. The attestation payload to the expected name/qname depending on the properties you want.

I think there in lies your problem? If you do that, how do you know that the public keys line up?

If I got that right, you need to know the template of the key you asked the TPM to create. The name isn't just a fingerprint of the crypto public details, it also carries semantics like, what attributes does it have, etc. It would be terrible if you asked for a key that is fixedTPM, and an attacker controlled tpm2_create just turned it down.

Then you can validate through tpm2_certify that the tpm did create a key you wanted, and it's in the TPM because the EK can see it. 

The responses attestation data signature would be validated against the EK.

Then the attestation payloads qname/name validated against the expected.

So to generate the expected name/qname to validate against, you would either ask for the output public template back from the TPM and validate that against the template you wanted, and calculate the name from that (since all the public crypto details are filled in), or start with your template and populate the crypto specific public data returned from the TPM.

I definitely see some utils here, you need to go from a TPM Public structure and get the pem and the name output.

**Comment by williamcroberts** [comment]
I filed these bugs off this ticket:
  - https://github.com/tpm2-software/tpm2-tools/issues/2053
  - https://github.com/tpm2-software/tpm2-tools/issues/2054
  - https://github.com/tpm2-software/tpm2-tools/issues/2055

I'm trying to capture everything from our conversations as bugs/features. Once we get through these conversations we can close these informational tickets and we'll have work items we can add to the release planning.

**Comment by osresearch** [comment]
After some study, I sort of understand how the the key name is used and agree that those issues are the right approach.

* Client sends the `TPM2B_PUBLIC` `ak.pub` structure, `ek.pub` and x509 `ek.crt` as part of the quote
* Server validates that the EK parameters in `ek.pub` match the EK cert in `ek.crt` using the improvements to `tpm2_print` (#2057) or perhaps a new program
* Server validates the `ak.pub` attributes (`fixedtpm`, `stclear`, etc) match its policy, also using the improvements to `tpm2_print` (#2057)
* Server validate the quote with `tpm2_checkquote` using the `ak.pub` (#2053)
* Server computes the name by sha256 hashing the `ak.pub` struct as part of generating the sealed credential with `tpm2_makecredential`  (#2054)  

In this protocol the `ak.pem` and `ek.pem` are unneeded since the information is already contained in the structures. The only cross checking that has to happen is that the `ek.crt` and `ek.pub`; perhaps that should be a new program to validate that they have the same parameters and key.

It's not clear to me how `tpm2_certify` works here. Which key is used to sign the output of `tpm2_certify`? How is its output verified by an outside party?

**Comment by williamcroberts** [comment]
EK Key will do it. Theirs really no 100% privacy, because its a not a group signing scheme and they dont share a key. Th original idea was that their would be a privacy CA, and only that CA knows if an AK is valid. So the attestor would ask the privacy CA if this AK was good or something like that. No one ever built it out.

Long store short, its all tied to the EK, and you can do the "whole privacy preserving" protocol, which was never built, so you'd have to build it. But almost no one cares, because most people want to know the TPM they are talking to.

@idesai is also working on a write up with examples he should be posting soon to help clarify this.

**Comment by osresearch** [comment]
I think this one has been resolved, other than for academic interest, since `tpm2_checkquote` can use the `ak.pub`, which can be hashed with sha256 to produce the name of the attestation key, so there is no longer a need to cross validate it.
