### ISSUE TITLE
unique data format is binary, make it easier to format

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2091]
The unique data is binary in the format of a TPMU_PUBLIC_ID, find a better format for this.

**Comment by rowanmoul** [comment]
Ideally one could simply pass a file that is read in a binary manner, and the size of the unique data is determined from the file size rather than the current method of having to append the size in the first two bytes.

Supporting text based unique data directly on the command line, or via STDIN would also be great.

**Comment by williamcroberts** [comment]
> Ideally one could simply pass a file that is read in a binary manner, and the size of the unique data is determined from the file size rather than the current method of having to append the size in the first two bytes.
> 
> Supporting text based unique data directly on the command line, or via STDIN would also be great.

I'm going to keep the binary format as is, so it's backwards compat and then add in some language for text based data, or maybe just a YAML file. Not sure. I'd like to see what the tss_ tools are doing in this regard, so then we can just do it the same way here.

**Comment by idesai** [comment]
In FAPI, the metadata about the blob is parsed from the json.
https://github.com/tpm2-software/tpm2-tss/blob/b6f7bce516f7cb5dc05d620a3d7b091931fc9898/src/tss2-fapi/tpm_json_deserialize.c#L3529
