### ISSUE TITLE
tpm2_eventlog fails on Google Cloud SecureBoot systems

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2204]
Booting a google cloud "ShieldedVM" in SecureBoot mode with the vTPM enabled produces an eventlog that is not parsable with the `tpm2 eventlog` in 2bfddf823a03ee39c46c2b3c526882b51b8c9004.
```
gcp% sudo cp /sys/kernel/security/tpm0/binary_bios_measurements events.bin
gcp% sudo tpm2 eventlog events.bin 
---
events:
ERROR: SpecID eventType must be EV_NO_ACTION
ERROR: failed to parse tpm2 eventlog
ERROR: Unable to run eventlog
```

It appears that the first event is of type 0x08, `EV_S_CRTM_VERSION`:
```
00000000: 00 00 00 00 08 00 00 00 14 89 f9 23 c4 dc a7 29  ...........#...)
00000010: 17 8b 3e 32 33 45 85 50 d8 dd df 29 02 00 00 00  ..>23E.P...)....
00000020: 00 00 07 00 00 00 01 00 00 80 d4 fd d1 f1 4d 40  ..............M@
00000030: 41 49 4d eb 8f c9 90 c4 53 43 d2 27 7d 08 35 00  AIM.....SC.'}.5.
00000040: 00 00 61 df e4 8b ca 93 d2 11 aa 0d 00 e0 98 03  ..a.............
00000050: 2b 8c 0a 00 00 00 00 00 00 00 01 00 00 00 00 00  +...............
00000060: 00 00 53 00 65 00 63 00 75 00 72 00 65 00 42 00  ..S.e.c.u.r.e.B.
00000070: 6f 00 6f 00 74 00 01 07 00 00 00 01 00 00 80 5a  o.o.t..........Z
00000080: bd 94 12 ab f3 3e 34 a7 9b 3d 1a 93 d3 50 e7 42  .....>4..=...P.B
```

I think this violates the [EFI Protocol spec](https://trustedcomputinggroup.org/wp-content/uploads/EFI-Protocol-Specification-rev13-160330final.pdf), which says that the first event *MUST* be _The   null   terminated   ASCII string “`Spec ID Event03`”_, so it might be a GCP issue, not a tpm2-tools issue.

Eventlog file is attached: [events.bin.gz](https://github.com/tpm2-software/tpm2-tools/files/5284658/events.bin.gz)

**Comment by josephlr** [comment]
I've figured out the issue here. Disclaimer: I work on vTPM attestation for Google Cloud.

As I noted in https://github.com/osresearch/safeboot/issues/73#issuecomment-699466048, Linux is simply requesting the old, SHA1-only format of the event log, which is what you're seeing above. As the EFI protocol spec notes, there are two formats of the EventLog, either of which can be used with TPM2.0. However, the old event log format can only be used to verify SHA1 pcrs.

The GCE Firmware maintains both log versions internally, but if the kernel doesn't ask for the agile log, that data gets deleted (as mandated by the spec). Luckily, updating the kernel to 5.3 or later will solve this issue.

As for tpm2-tools, this library _could_ support parsing both formats of the event log. For example, [go-attestation](https://github.com/google/go-attestation) determines the format by [attempting to parse the first entry](https://github.com/google/go-attestation/blob/master/attest/eventlog.go#L423-L448), and then parses either the new or old style of log. However, if you only have the old format, you can only use SHA1 PCRs, which has security issues due to the risk of hash collision.

**Comment by osresearch** [comment]
Thanks for tracking this down, @josephlr .  For future reference, the system under test was Debian 10 Buster, kernel 4.19 (image debian-10-buster-v20200910 with SecureBoot enabled).  Since it is not a tpm2-tools bug, I'll close this issue.
