### ISSUE TITLE
Question: tpm2 eventlog: verifying TPM_GENERATED and fake/forged entries?

### ISSUE THREAD

**Issue by IAXES** [tpm2-software/tpm2-tools#2252]
# Question

Does the TPM2 event log parser (i.e. `tpm2 eventlog`) do any manner of data verification (i.e. beyond its size/format sanity checks)? For example, does it (or does it have the ability to):

- Validate each entry in the log against the TPM2.0 device (i.e. check if `TPM_GENERATED` is present in the entry, and ask the TPM2.0 device to validate the entry).
- Check if entries in the log are out-of-order?

---

# Background

In short, I'm writing a simple app that uses the output of the (parsed) event log as a (hopefully) more granular "system health metric" than **just** looking at the PCRs (i.e. user can play with settings on a device that would change BIOS settings, resulting in some PCR values changing, and by extension, their hashes changing). The idea is to extend a basic [TPM2.0 remote attestation example](https://github.com/idesai/tpm2-attestation), and if the "golden PCR values" don't match as expected, to walk through the event log to establish a fuzz metric, e.g.:

- Auth server receives PCRs, event log dump, etc.; all signed by the remote TPM2.0-enabled device.
- Auth server attempts remote attestation; fails due to PCR mismatch.
- Auth server has on-site DB/mapping to associate EK with AIK for remote device.
- Auth server walks through event log.

This is primarily intended to detect specific types of product tampering (i.e. resetting BIOS settings or upgrading/downgrading the BIOS on specific devices/workstations).

**Comment by idesai** [comment]
@IAXES no, but have you looked at [keylime](https://keylime.dev)?

**Comment by IAXES** [comment]
> 
> 
> @IAXES no, but have you looked at [keylime](https://keylime.dev)?

No, but it definitely looks interesting.

**Comment by idesai** [comment]
Not sure, @lukehinds can you please comment?

**Comment by huang195** [comment]
@IAXES are you getting anywhere with this problem? For remote attestation, you need a quote and an eventlog. The quote contains PCR values that are signed by the TPM device, so they can be trusted. AFAIK, the eventlog cannot be signed by the TPM device in a similar way, so its content needs to be verified. Since `tpm2_eventlog` can replay the extend operation using the hash of each event in the eventlog, their final value can be compared with those in quote, thus preventing the tempering of the hash values in the eventlog. However, an attacker can still modify the "payload" of an event to trick the script that is parsing the eventlog (when PCR values don't match golden values). 

@idesai looking at the code, it doesn't seem that it is doing any validation of the event "payload". Please correct me if I misunderstood.

**Comment by IAXES** [comment]
> 
> 
> @IAXES are you getting anywhere with this problem? For remote attestation, you need a quote and an eventlog. The quote contains PCR values that are signed by the TPM device, so they can be trusted. AFAIK, the eventlog cannot be signed by the TPM device in a similar way, so its content needs to be verified. Since `tpm2_eventlog` can replay the extend operation using the hash of each event in the eventlog, their final value can be compared with those in quote, thus preventing the tempering of the hash values in the eventlog. However, an attacker can still modify the "payload" of an event to trick the script that is parsing the eventlog (when PCR values don't match golden values).
> 

@huang195 Thank you. If I can confirm this behavior, it helps significantly. If it's possible to validate the "payload" as well (i.e. detect tampering), that would 100% resolve this open question.

On a semi-related topic, is it possible to (securely) measure into the PCRs (PCR #7, IIRC) the signature of the kernel and/or initrd used to boot the system? The ultimate goal is to ensure that only an approved initrd and/or bzImage/vmlinux/kernel is used to boot the system, along with an approved kernel CLI args list, and approved BIOS vendor + version. However, I'd like to let users/devs upgrade the OS version, so having the PCR pegged against the signature used to sign the kernel/initrd would allow me to have "golden PCRs" pre-created in advance, while still allowing customers to use different kernel/initrd images (supplied by me), which would allow remote attestation to work with software/kernel updates (without requiring me being present on-site to re-seal the policy and re-generate/extract new "golden PCRs").

**Comment by huang195** [comment]
@IAXES the issue is not quite that straight forward. For certain event types, e.g., EV_EFI_BOOT_SERVICES_APPLICATION, that are used to measure shim/grub before they're allowed to run, their digest is calculated based on the shim/grub code loaded into memory and thus cannot be validated from the eventlog alone. On the other hand, there are other event types where the digest is based only on the payload, e.g., EV_EFI_VARIABLE_DRIVER_CONFIG, EV_SEPARATOR, etc. To make the complex situation worse, different platform vendors have small variations of what data the digest is based upon, and this is largely due to ambiguity in the spec document. 

As for kernel/initrd, I believe these are measured to PCR 9 using EV_IPL event type (at least on my machine). I believe verifying the eventlog using pre-calculated digest should work in your situation.

**Comment by IAXES** [comment]
@huang195  Thank you. I believe I have enough information to close this issue.

One additional question: in addition to `<https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/>`, what other venues are used by TPM devs/contributors/maintainers such as yourself? I only notice the occasional post at the forum linked above, and was wondering if the `tpm2-software` devs (or the Linux TPM2.0 dev community in general) has a mailing list, Slack instance, etc.; that I could use for generic Q&A that doesn't necessarily fit here (i.e. in issues in this GitHub project). I've noticed the "OSFW" Slack channel seems to be a good candidate, but I'm curious if there are additional resources I should check out.

**Comment by williamcroberts** [comment]
> @huang195 Thank you. I believe I have enough information to close this issue.
> 
> One additional question: in addition to `<https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/>`, what other venues are used by TPM devs/contributors/maintainers such as yourself? I only notice the occasional post at the forum linked above, and was wondering if the `tpm2-software` devs (or the Linux TPM2.0 dev community in general) has a mailing list, Slack instance, etc.; that I could use for generic Q&A that doesn't necessarily fit here (i.e. in issues in this GitHub project, such as questions about measured boot that fall outside the scope of this GitHub project). I've noticed the "OSFW" Slack channel seems to be a good candidate, but I'm curious if there are additional resources I should check out.

Their are also two other resources I am aware of:
1. tpm.dev. Their is a weekly call, some folks on their have a ton of info. Most are lurking on the mailing list though.
2. You can always reach out the the TCG Working Groups:
  - https://trustedcomputinggroup.org/work-groups/trusted-platform-module/
  - They have a contact email in the bottom, I would imagine you can just ask for it to be routed to the TPM Working Group.

**Comment by IAXES** [comment]
@williamcroberts Thank you!
