### ISSUE TITLE
How to convert tpm2_hmac output to openssl format?

### ISSUE THREAD

**Issue by danielwangksu** [tpm2-software/tpm2-tools#2283]
Hi there,

I'm trying to use tpm2_hmac to replace openssl dgst -hmac output.

using openssl I got the following string:
```
openssl dgst -hmac [KEY] -sha256 -output [OUTPUT_FILE] [INPUT_FILE]
HMAC-SHA256(random_file_generated/random_file_256_1.bin)= d8ec780d23d9454bb527d46cf968e525290b975345a5b1c168748ac4bf9cc947
```

using tpm2_hmac I got binary output
```
tpm2_hmac -c 0x81000002 -g sha256 [INPUT_FILE] -o [OUTPUT_FILE]
```

is there a way to make those two outputs compatible? Ideally convert tpm2_hmac binary output to string format. Thank you very much!

**Comment by williamcroberts** [comment]
```bash
echo "HMAC-SHA256(input.dat)=$(tpm2_hmac -c key.ctx -g sha256 input.dat | xxd -p -c256)"
HMAC-SHA256(input.dat)=6a2a19a899956fd1539a6bf4c3bac8864e4e40b5915c036d65a330beaee350dd
```

You could even wrap it up into a function:
```bash
tpm2_ossl_hmac key.ctx sha256 input.dat 
HMAC-SHA256(input.dat)=6a2a19a899956fd1539a6bf4c3bac8864e4e40b5915c036d65a330beaee350dd
```

```bash
tpm2_ossl_hmac() {
    key="$1"
    alg="$2"
    file="$3"
    echo "HMAC-${alg^^}($file)=$(tpm2_hmac -c $key -g $alg $file | xxd -p -c256)"
}
```

tpm2_hash also suffers from the fact that their is no way to get the OSSL style output. We could add format options to the tools, so one can specify `--format=hex|ossl|bin' or something like that. But their are good ways using the commandline to accomplish it rather than adding yet another option and thing to maintain to the tools themselves.
