### ISSUE TITLE
OpenSSL 3.0 Support

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2737]
Compile against OpenSSL 3.0, fix and verify.

**Comment by idesai** [comment]
Duplicate #2354

**Comment by gotthardp** [comment]
Just a status report: I am working on this, but it is more difficult than I thought, so it may take "some time" before it's ready for review. It should be ready before the final OpenSSL 3.0 is released though.

**Comment by gotthardp** [comment]
Status update: With the latest master the tpm2-tools successfully build against OpenSSL 3.0 even when it is built with the `no-deprecated` option. All tests pass, except `test/integration/tests/X509certutil.sh`, which is due to https://github.com/tpm2-software/tpm2-tools/issues/2813. This is yet to be fixed, but everybody interested should be able to play with TPM2 and OpenSSL 3.0 now.

BTW, the final OpenSSL 3.0.0 is expected next week.

**Comment by gotthardp** [comment]
The OpenSSL 3.0 support is now complete. All tests pass.

(Release 3.0.0 will be on Tuesday the 7th of September 2021 if run-checker and CI builds have been clean for two days.)

**Comment by idesai** [comment]
@gotthardp, can we close this?

**Comment by gotthardp** [comment]
Yes, the upcoming 5.2 release should be "3.0 ready".

**Comment by idesai** [comment]
> Yes, we can. The upcoming 5.2 release should be "3.0 ready".
> The #2354 can be closed too.

Thank you!
