### ISSUE TITLE
Change SPI speed frequency

### ISSUE THREAD

**Issue by x-logic-iot** [tpm2-software/tpm2-tools#2786]
Is it possible to change the spi speed frequency?

**Comment by williamcroberts** [comment]
That would be at a very different level and functionality than what this project provides. I would look more at how the SPI bus interfaces in the kernel work. Im going to close this, because this forum isn't going to be able to help much. I'd hit either our mailing list, perhaps someone knows offhand, or a kernel mailing list.

**Comment by x-logic-iot** [comment]
Thank you for your answer. I managed to do this by changing the spi-max-frequency parameter in the dts file
