### ISSUE TITLE
TPM2.0 encrypted SPI data lines

### ISSUE THREAD

**Issue by x-logic-iot** [tpm2-software/tpm2-tools#2796]
Hello,

could you please explain if the SPI lines that communicate with TPM2.0 use dynamic encryption? If yes, where could I read more about it? 

Is it possible to get plaintext with SPI data line detection by oscilloscope? How secure is TPM2.0 against physical attacks?

**Comment by williamcroberts** [comment]
Yes it is supported. If you want to encrypt data over the SPI lines you need to use encrypted sessions. If you look at the Architecture guide, it describes the inner workings in Section 21 "Session based encryption":
  - https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf
 
If you're using the tools, you can use `tpm_startauthsession` to start an encryption session and use the -S parameter. However, you should do something to verify that the key is the key you expect so your not in a MITM situation. Since the context file is used for specifying the key, you can just do some type of sign/verify with the tools and keep using that context file.
 
If you're doing it in the C API, the FAPI does it automatically. If you use ESAPI you need to use Esys_StartAuthSession. If you use the SAPI, you need to roll all the crypto, so it's not really feasible for most users.

If you can Man in the Middle (MITM) the TPM on the bus, whether its SPI, LPC, I2C, etc, and encryption is not used, it's possible to view the data.

TPM 2.0 devices do not need to be tamper resistant, but some are. Many vendors make tamper resistant TPM's like Infineon's OPTIGA™ TPM SLI 9670.

Questions like this are usually better asked on the mailing list, you'll get more people to way in:
  -https://lists.01.org/postorius/lists/tpm2.lists.01.org/

**Comment by x-logic-iot** [comment]
Thank you very much for your response
