### ISSUE TITLE
tss2_provision: destructive?

### ISSUE THREAD

**Issue by fansari** [tpm2-software/tpm2-tools#3139]
When I run tss2_provision I have to setup everything again.

Is it meant to be that way or is it possible like with Ledger Nano to use some seed to get the original state back?

**Comment by williamcroberts** [comment]
`tss2_provision` is a non-destructive operation and will fail with `TSS2_FAPI_RC_ALREADY_PROVISIONED` if it's already provisioned. So the only way to run it twice is if the profile directory is deleted or you configure it to use some other location in the fapi-config(5) fies. See the code around line:
  - https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-fapi/api/Fapi_Provision.c#L240
 
As far as seeds go, The TPM is made up of hierarchies which have an initial seed value, the hierarchies are as follows:
Owner: Where most things are done, like the Storage Root Key (SRK). All child keys are made below the SRK. Think of the SRK as work space for every application.
Endorsement: The Endorsement Key is generated and matches the Manufacturers Certificate (proves provenance of the TPM)
Platform: For the operating system, not really accessible to userspace in most environments.
Null: Gets a new seed on each boot.

The seeds can be modified through:
Owner: TPM2_Clear
Endorsement: Firmware Update / ChangeEPS command if supported.
Platform: ChangePPS command if supported, probably some other way I don't know.
Null: Each TPM reboot

FAPI's tss2_provision, AFAICT, does not call Esys_Clear (TPM2_Clear), so none of the initial seed state should be destroyed, but if you lost the meta data in the FAPI store, the keys cannot be recreated without it. The SRK, since it's a primary key, will use the same seed, so given the same template for creating the key, you get the same key every time. So given the same SRK and the same metadata for subordinate keys, you could recreate the state. TPM2_Clear essentially deletes all this since you cannot recreate the SRK the other keys we're created under.

Here's an example, notice that each tpm2_createprimary key generates the same rsa key (look at the rsa value)?
```bash
tpm2_createprimary | grep rsa:
rsa: cbe387d7...7ac13

tpm2_createprimary | grep rsa:
rsa: cbe387d7...7ac13

tpm2_createprimary | grep rsa:
rsa: cbe387d7...7ac13
```
Now if we run `tpm2_clear`, we get a different key:
```bash
tpm2_clear 
wcrobert@wcrobert-mobl1:~/workspace/tpm2-tss/src/tss2-fapi$ tpm2_createprimary | grep rsa:
rsa: 9c4c3c...9506b5
```

@AndreasFuchsTPM or @JuergenReppSIT any info to add on this?

**Comment by fansari** [comment]
As far as I understand this I should not loose the content of /var/lb/tpm2-tss after provisioning.

One question about the primary keys in general: in example documentations I found that they go to addresses like 0x81010001.

But I found some documentation saying that this 0x8101 range is for endorsement keys.

https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf

Is this the correct space anyway or should they go somewhere into 0x8100?

**Comment by williamcroberts** [comment]
> As far as I understand this I should not loose the content of /var/lb/tpm2-tss after provisioning.
> 
> One question about the primary keys in general: in example documentations I found that they go to addresses like 0x81010001.
> 
> But I found some documentation saying that this 0x8101 range is for endorsement keys.
> 
> https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf
> 
> Is this the correct space anyway or should they go somewhere into 0x8100?

So their is the Endorsement Key (EK) and the Manufacturer Certificate that tss_provision sets up. The Endorsement Key is usually persisted at the address of `0x81010001`. The SRK is persisted to 0x81000001, see table 2 of:
  -  https://trustedcomputinggroup.org/wp-content/uploads/TCG-TPM-v2.0-Provisioning-Guidance-Published-v1r1.pdf

**Comment by fansari** [comment]
I have started from scratch and checked what is setup and where.

```
0x81000000 => from tss_provisioning
0x81000001 => from tpm2_ptool iniit
```
So there is no EK after provisioning.

**Comment by williamcroberts** [comment]
> I have started from scratch and checked what is setup and where.
> 
> ```
> 0x81000000 => from tss_provisioning
```
That's not what it should be doing, are you sure?
If you look at the two profiles [1], the default configuration is to have them both at 0x81000001.
Some old version of tpm2_ptool init had it wrong at 0x81000000, this was versions BEFORE 1.4.0.
This was fixed on 1.4.0 and later releases.

```
> 0x81000001 => from tpm2_ptool init
> ```
> 
> So there is no EK after provisioning.
> 

Not by default, but you can request the profile persist the EK in the ek_template by adding the handle
to the ek_template field. Look at the srk_template for examples, its just the hex address.

> I have now created a primary key and loaded it into 0x81000002.

Ok, why? What's the purpose of this key?

[1] https://github.com/tpm2-software/tpm2-tss/tree/master/dist/fapi-profiles

**Comment by fansari** [comment]
I have tried again. It is in fact the other way round:

Before tss_provision there is no persistent handle. After tss_provision I find this:

```
[fansari@bat keys]$ tpm2_getcap handles-persistent
- 0x81000001
```

Then after I run "tpm2_ptool init" it looks like this:

```
[fansari@bat ssh]$ tpm2_getcap handles-persistent
- 0x81000000
- 0x81000001
```
Regarding additional keys I only did this because I saw this in examples.

Maybe it is enough to use the 0x81000001. I tested this HMAC example with this key and it also works.

**Comment by williamcroberts** [comment]
@fansari do you have any opens that you still need to figure out here that I can help with?

**Comment by williamcroberts** [comment]
> Maybe it is enough to use the 0x81000001

Yeah thats the default SRK, just set it like you did with `--primary-handle=0x81000001` and everything should work as expected and no extra primary objects laying around on the TPM.

**Comment by fansari** [comment]
Thank you. I will close this ticket at this point.
