### ISSUE TITLE
Distribute generated man pages in release tarball

### ISSUE THREAD

**Issue by mgerstner** [tpm2-software/tpm2-tools#925]
The current release tarballs require `pandoc` for building the man pages. This is quite a big dependency (pandoc requires a haskell stack). It would be easier for packaging to ship the generated man pages in the release tarball.

This can be achieved by adding `dist_man_MANS := $(man1_MANS)` to Makefile.am. However it conflicts with the current conditional `HAVE_PANDOC`. If pandoc isn't present then the man pages will not be installed in the context of the resulting release tarball, although they are already generated.

If have not found a clean solution to address this within automake. One approach might be to always expect `pandoc` to be present when building the source tarball. Maybe you have a good idea how to approach this.

**Comment by williamcroberts** [comment]
On one hand, if your going to distribute part-of-the build, it would seem analogous to building the C files as well. But I get where you're coming from. When you're cross-compiling (which I have no idea how to do with autotools) it should be tetsting for host pandoc (if it isn't that's wrong), and then using the host to build the manpages. What build machine can't you just do "apt-get install pandoc"...

On the other hand, since it's not platform specific, just generate it and release it.

I wonder what @martinezjavier thinks, as he is a downstream packager, and has more understanding about these types of issues than I do, thoughts?

**Comment by mgerstner** [comment]
@williamcroberts, it is actually an issue in our SUSE build environment. We do not have the pandoc and haskell packages in our enterprise repositories. Therefore I had to disable man page installation for tpm2-tools there for the moment.

My only options to get the man pages back there would be to add pandoc & friends to our enterprise repositories (big issue) or packaging the generated man pages separately myself (maintenance burden).

**Comment by martinezjavier** [comment]
@mgerstner thanks for bringing this, I agree with you. In fact, we had the exact same issue in our enterprise repository. For now the man pages are added as a patch, but we need to find a better solution.

@williamcroberts maybe what we could do is to generate the distribution tarball using `make distcheck` instead of `make dist`? That way the man pages will be generated and added to the distribution tarball.

And remove the `HAVE_PANDOC` check in the `Makefile.am` as mentioned by @mgerstner.

What do you think?

**Comment by williamcroberts** [comment]
I have 2 concerns with that:
1. Removing the PANDOC check. Someone could create a release tarball without the manpages.
2. distcheck will add binaries, right? Which I don't want to do.

What if we hooked make dist and checked for pandoc. We don't want someone to accidentally create a release tarball with out these.

The second part is adding the generated man-pages into the dist image, not sure if it's as simple as adding them to EXTRA_DIST.

This Q&A has some information, albeit not turn key, but might help us head in the right direction:
https://stackoverflow.com/questions/18327461/automake-generated-source-files-and-vpath-builds

IRC, tpm2-tss is now generating AUTHORS file via git, and I would imagine that get's in their dist tarball, so you can also look there.

@mgerstner It will likely be awhile before I look at this, but feel free to propose a patch.

**Comment by williamcroberts** [comment]
Looks like we can just use the dist hook to:
1. check that pandoc is enabled (have a dependency on the man-pages)
2. copy them into the dist

See: https://ftp.gnu.org/old-gnu/Manuals/automake-1.6.1/html_chapter/automake_15.html
